export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_TIMETABLES = "FETCH_TIMETABLES";
export const FETCH_TIMETABLES_SUCCESS = "FETCH_TIMETABLES_SUCCESS";
export const FETCH_TIMETABLES_ERROR = "FETCH_TIMETABLES_ERROR";
export const ADD_TIMETABLES = "ADD_TIMETABLES";
export const ADD_TIMETABLES_SUCCESS = "ADD_TIMETABLES_SUCCESS";
export const ADD_TIMETABLES_ERROR = "ADD_TIMETABLES_ERROR";
export const DELETE_TIMETABLES = "DELETE_TIMETABLES";
export const DELETE_TIMETABLES_SUCCESS = "DELETE_TIMETABLES_SUCCESS";
export const DELETE_TIMETABLES_ERROR = "DELETE_TIMETABLES_ERROR";
export const SEARCH_TIMETABLES = "SEARCH_TIMETABLES";
export const SEARCH_TIMETABLES_SUCCESS = "SEARCH_TIMETABLES_SUCCESS";
export const SEARCH_TIMETABLES_ERROR = "SEARCH_TIMETABLES_ERROR";

export const FETCH_TEACHER = "FETCH_TEACHER";
export const FETCH_TEACHER_SUCCESS = "FETCH_TEACHER_SUCCESS";
export const FETCH_TEACHER_ERROR = "FETCH_TEACHER_ERROR";

export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_ERROR = "FETCH_COURSE_ERROR";

export const FETCH_CLASS = "FETCH_CLASS";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_ERROR = "FETCH_CLASS_ERROR";

export const FETCH_DEVICES = "FETCH_DEVICES";
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_DEVICES_ERROR = "FETCH_DEVICES_ERROR";
export const ADD_DEVICES = "ADD_DEVICES";
export const ADD_DEVICES_SUCCESS = "ADD_DEVICES_SUCCESS";
export const ADD_DEVICES_ERROR = "ADD_DEVICES_ERROR";
export const CHANGE_DEVICES = "CHANGE_DEVICES";
export const CHANGE_DEVICES_SUCCESS = "CHANGE_DEVICES_SUCCESS";
export const CHANGE_DEVICES_ERROR = "CHANGE_DEVICES_ERROR";

export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_ERROR = "FETCH_ACCOUNTS_ERROR";
export const ADD_ACCOUNTS = "ADD_ACCOUNTS";
export const ADD_ACCOUNTS_SUCCESS = "ADD_ACCOUNTS_SUCCESS";
export const ADD_ACCOUNTS_ERROR = "ADD_ACCOUNTS_ERROR";

// export const FETCH_ACCOUNT_INFOR = "FETCH_ACCOUNT_INFOR";
// export const FETCH_ACCOUNT_INFOR_SUCCESS = "FETCH_ACCOUNT_INFOR_SUCCESS";
// export const FETCH_ACCOUNT_INFOR_ERROR = "FETCH_ACCOUNT_INFOR_ERROR";
