export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_TIMETABLES = "FETCH_TIMETABLES";
export const FETCH_TIMETABLES_SUCCESS = "FETCH_TIMETABLES_SUCCESS";
export const FETCH_TIMETABLES_ERROR = "FETCH_TIMETABLES_ERROR"; 