export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_TIMETABLES = "FETCH_TIMETABLES";
export const FETCH_TIMETABLES_SUCCESS = "FETCH_TIMETABLES_SUCCESS";
export const FETCH_TIMETABLES_ERROR = "FETCH_TIMETABLES_ERROR"; 

export const FETCH_TEACHER = "FETCH_TEACHER";
export const FETCH_TEACHER_SUCCESS = "FETCH_TEACHER_SUCCESS";
export const FETCH_TEACHER_ERROR = "FETCH_TEACHER_ERROR";

export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_ERROR = "FETCH_COURSE_ERROR";

export const FETCH_CLASS = "FETCH_CLASS";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_ERROR = "FETCH_CLASS_ERROR";